<?php
/**
 * Index page template
 * 
 * @var string $testVar Variable for test
 *
 * @see \ShadeApp\Controller\Index::indexAction()
 */
?>
<h1><?=$pageTitle?></h1>
<p>
    This is a dummy page of your application. If you able to see it in a browser it means that skeleton application
    was generated successfully and web server properly configured to handle requests.
</p>
<p>
    You are ready to start coding. Go for it!
</p>
<p>
    Shade project web page: <a href="https://github.com/Polosa/shade-framework-core">https://github.com/Polosa/shade-framework-core</a>.
</p>