<?php
/**
 * Cli
 *
 * @see \Shade\Controller\Cli::indexAction()
 */
?>
<?php if ($wrongArgs) :
    ?><?=$cliFileName?> new ApplicationName ApplicationRootPath<?php
elseif ($skeletonPathIsExistingFile) :
    ?><?=$skeletonPath?> is existing file<?php
elseif ($errorWhenCreatingDir) :
    ?>Can't create application directory <?=$skeletonPath?><?php
else :
    ?>Skeleton application <?=$skeletonName?> generated and stored under <?=$skeletonPath?><?php
endif ?>

